name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: CHECK VERCEL_ORG__ID
        run: |
            if [ -z "${{ secrets.VERCEL_ORG_ID }}" ]; then
            echo "VERCEL_ORG_ID is not set or empty."
            else
                echo "VERCEL_ORG_ID is set."
            fi
      - name: CHECK VERCEL_PROJECT_ID
        run: |
            if [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "VERCEL_PROJECT_ID is not set or empty."
            else
                echo "VERCEL_PROJECT_ID is set."
            fi
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
